GET http://127.0.0.1:8000/api/members
Content-Type: application/json

{
    "with_tags": ""
}

###

GET http://127.0.0.1:8000/api/members/2
Content-Type: application/json

{
    "with_tags": ""
}

###


GET http://127.0.0.1:8000/api/

###

DELETE http://127.0.0.1:8000/api/members/8

###

POST http://127.0.0.1:8000/api/members
Content-Type: application/json

{
  "first_name": "Sam",
  "email": "samdoe@example.com",
  "birthdate": "1990-11-01"
}

###

PUT http://127.0.0.1:8000/api/members/2 HTTP/1.1
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "birthdate": "1990-01-01"
}
